### PR TITLE
Params Added

### PR DESCRIPTION
**Pull request by Balamir**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please could you rebase and force push to avoid the merge commit?

**Comment by GrahamCampbell** [comment]
Ping @notifymehq/owners for review.

**Comment by Balamir** [comment]
For future?

**Comment by GrahamCampbell** [comment]
> For future?

What do you mean?

**Comment by jbrooksuk** [comment]
> What do you mean?

Huh?

**Comment by jbrooksuk** [comment]
Also a :+1: for me.

**Comment by GrahamCampbell** [comment]
image

**Comment by Balamir** [comment]
(; Haha, funny.

I'm using Github for Windows and I couldn't find that option. So, totally it's fault.

(; Yes, a :+1: for you, @jbrooksuk

**Comment by GrahamCampbell** [comment]
Now there are even more merge commits. ;(

**Comment by GrahamCampbell** [comment]
Just open the cli and run the git commands manually. GitHub for windows doesn't have a way to force push.

**Comment by Balamir** [comment]
Ok, I'll try.

**Comment by Balamir** [comment]
I tried but it's says "everything up-to-date". I guess I'm doing something wrong. Sorry :(

sshot-73

So, I couldn't figured out.

**Comment by GrahamCampbell** [comment]
You need to `git pull --rebase upstream master` first.

**Comment by GrahamCampbell** [comment]
If it says that doesn't exist, run `git remote add upstream https://github.com/notifymehq/notifyme`.

**Comment by Balamir** [comment]
Thats the result:

sshot-74

**Comment by GrahamCampbell** [comment]
Why the guzzle change?

**Comment by Balamir** [comment]
The new version of guzzlehttp is doesn't pass the 'body' option for the request. It's deprecated and changed to 'form_params'. When I try, it's give an error:

Passing in the "body" request option as an array to send a POST request
has been deprecated. Please use the "form_params" request option to send
a application/x-www-form-urlencoded request, or a the "multipart"
request option to send a multipart/form-data request.

So, I changed it.

**Comment by GrahamCampbell** [comment]
We need to support both versions of guzzle.

**Comment by joecohens** [comment]
``` php
if (version_compare(ClientInterface::VERSION, '6') === 1) {
    $request['form_params'] = $params;      
} else {
    $request['body'] = $params;
}
```

/cc @Balamir

**Comment by GrahamCampbell** [comment]
There might be cases in the other adapters too.

**Comment by Balamir** [comment]
Could we use like that:

```
    // GuzzleHttp Version < 6
    $param_querystring = 'body';
    // GuzzleHttp Version = 6
    if ( version_compare( ClientInterface::VERSION, '6' )  === 1 ) {
        $param_querystring = 'form_params';      
    }
```

/cc @joecohens 

This should be apply to Pushover, Twilio, Yo adapters too.

**Comment by joecohens** [comment]
@Balamir maybe it's simpler

``` php
$requestBodyKey = (version_compare( ClientInterface::VERSION, '6' ) === 1) ? 'form_params' : 'body';
```

Also can you squash please?

**Comment by Balamir** [comment]
> Also can you squash please?

@joecohens What do you mean?

**Comment by jbrooksuk** [comment]
> @joecohens What do you mean?

Make it into one commit :)

**Comment by Balamir** [comment]
> Make it into one commit :)

(; I see now.

So, how can I revert and combine all those commits with cli? Sorry I'm not a pro with git.

**Pull request closed without merging**
