### PR TITLE
Improved the readme

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by frankdejonge** [comment]
@GrahamCampbell the composer install stuff should just be:

``` bash
composer require vendor/package
```

**Comment by GrahamCampbell** [comment]
I know it **could** be that, be I don't like that. I prefer to edit composer.json files. That way I can have dependencies order how I want them. :)

**Comment by GrahamCampbell** [comment]
We can always change this later if lots of people prefer using the command to require packages.

**Comment by frankdejonge** [comment]
@GrahamCampbell you are the last one from whom I'd expect personal preference to block best practices ;)

**Comment by GrahamCampbell** [comment]
It's not a best practice though? It's just a preference.

**Comment by frankdejonge** [comment]
It is though. Not only is it more sustainable/future-proof, it also set's the correct version constraint depending on the rest of the composer settings the consuming dev has specified.

**Comment by GrahamCampbell** [comment]
Hmmm, I'll think about it, lol.

**Comment by frankdejonge** [comment]
Come on, @GrahamCampbell, you know I'm right :dancer:

**Comment by rdohms** [comment]
It actually is the recommended way.

Not only does it do auto-mapping to the proper version which is nice and handy. But it also runs a controlled install that will affect less of the other dependencies as possible, since most people simply run composer update or install after editing the composer.json, this can lead to a lot of unexpected updates. So rather than trying to grok all that, `composer require` will handle everything in a atomic action.

Keeping all dependencies "is alphabetical order" on the other hand is a preference and has not real practical purpose since you can get all that same information using `composer show --installed` and then remove using `composer remove package`.. hence touching the json file as little as possible, leading to less syntax errors and such.

**Pull request merged**
