### PR TITLE
Proposed Rename

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Not sure about this. :/

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Meh, looks rubbish.

**Comment by joecohens** [comment]
Rename to `notifymehq/notifyme` ?

**Comment by GrahamCampbell** [comment]
Yeh

**Comment by GrahamCampbell** [comment]
You'll need to actually delete the old package first. If the delete button is missing, then contact packagist support and they can remove it for you.

**Comment by joecohens** [comment]
Done :)

**Comment by jbrooksuk** [comment]
Looks good!

**Pull request closed without merging**
