### PR TITLE
Added NotifymeHq Mail gateway

### PR DESCRIPTION
**Pull request by gpassarelli**
Hi guys, so I've created the gateway for Mail using NotifyMeHQ, let me know what you guys think.

Here is the link of if:
https://github.com/descubraomundo/notifymehq-mail

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
We intentionally removed mail support, sorry.

**Comment by GrahamCampbell** [comment]
Looks like your implementation is incorrect because the message isn't a string.

**Comment by gpassarelli** [comment]
Really?? May I know way?
Em seg, 16 de nov de 2015 às 11:49, Graham Campbell <
notifications@github.com> escreveu:

**Comment by GrahamCampbell** [comment]
That's essentially what we ran into. In reality, people wish to send multiple content types or attatch stuff, so notifyme is unsuitable for mail. Also, I think you mean "array" rather than "Array". They're very different. "array" is a php native type, but "Array" is an object.

**Comment by GrahamCampbell** [comment]
> Really?? May I know way?

Message must be a string.

**Comment by GrahamCampbell** [comment]
Your gateway does NOT implement https://github.com/notifymehq/contracts/blob/master/src/GatewayInterface.php correctly, basically.

**Comment by gpassarelli** [comment]
I was replying for my phone and by email, so when I asked 

> Really?? May I know way?

It was regarding why you guys removed the email support and not why my implementation was not correct.

And what do you mean with: 

> send multiple content types or attatch stuff, so notifyme is unsuitable for mail

**Comment by jbrooksuk** [comment]
Because basically Email has too many variables to make into one simple implementation.

**Comment by gpassarelli** [comment]
I mean, the only diference is that beside the message it self , you also need to specify a subject.  All the others are all optionals. And even for that, you could provide all this settings for your `$notifierFactory` and your implementation for email, it would still be only: 

```
$mailNotifier->notify('email@example.com', 'This is my email notification');
```

**Comment by gpassarelli** [comment]
So I've updated the gateway to implement the gateway contract correctly and to make into one simple implementation. 

If you guys like it and want to make it official, fee free for it. If not, I'll release as an unofficial version of it. Because It makes sense for us to use it like that and maybe for someone else, but it's your call.

https://github.com/descubraomundo/notifymehq-mail

**Comment by GrahamCampbell** [comment]
I just don't agree that this makes sense. The whole idea of notifyme is that developers should not care that the message is ending up as an email, and normally emails have very specific extra formatting, more like letters, so notifyme isn't suitable.

**Comment by GrahamCampbell** [comment]
Notifyme is meant to be more like a texting people type of thing.

**Comment by gpassarelli** [comment]
Ok.

**Pull request closed without merging**
